In [1]:
list_1 = [[1, 2],[5, 6]]


In [2]:
list_2 = [[3, 4],[7, 8]]


In [3]:
list_3 = [[9, 10, 11, 12]]

In [8]:
import numpy as np
a = np.hstack((list_1, list_2))

In [10]:
print (a)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b = list_3

In [12]:
np.vstack((a,list_3))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])