In [2]:
a =  ((500//7) % 5) ** 3

In [3]:
a

1

In [1]:
a = 10
b = 15
for fizzbuzz in range(a, b):
    if fizzbuzz % 3 == 0 and fizzbuzz % 5 == 0:
        print("fizzbuzz")
        continue
    elif fizzbuzz % 3 == 0:
        print("fizz")
        continue
    elif fizzbuzz % 5 == 0:
        print("buzz")
        continue
    print(fizzbuzz)

buzz
11
fizz
13
14


In [1]:
list_1 = [2,3,4,5]

In [2]:
list_2 = [7,8,9,6]

In [8]:
import numpy as np
array_1 = np.array([list_1])
array_2 = np.array([list_2])
array_3 = array_1 * array_2

In [9]:
print (array_3)

[[14 24 36 30]]


In [31]:
import numpy as np
array_multipleof5 = np.arange( 5, 55, 5)


print(array_multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


In [34]:
import numpy as np

n = 2

chkrboard = np.tile(n,n)

print(chkrboard)

[2 2]


In [35]:
array_1 = [1 2 3 5 4 6 7 8 5 3 2]
print(array_1[0::2])

SyntaxError: invalid syntax (<ipython-input-35-4852fd658f56>, line 1)

In [6]:
import numpy as np
npanarray = np.array ([[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]])

SyntaxError: invalid syntax (<ipython-input-6-5e92c989603b>, line 2)

In [7]:
list1 = [[11,12,13,14], [21,22,23,24], [31,32,33,34]]

In [8]:
import numpy as np
npanarray = np.array(list1)

In [9]:
print(npanarray)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


``` Output 1:
[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]
```


In [11]:
col_first = print(npanarray[:, :1])

[[11]
 [21]
 [31]]


In [12]:
row_first = print(npanarray[:1, :])

[[11 12 13 14]]


In [23]:
row_last = print(npanarray[-1:])

[[31 32 33 34]]
